[2023-06-29 21:39:55,973] root - INFO - 'train_evaluate' function started
[2023-06-29 21:39:55,973] root - INFO - Reading all params from config_path
[2023-06-29 21:39:55,991] root - INFO - parameters readed from config_path successfully!!!
[2023-06-29 21:39:55,991] root - INFO - train data read successfully-->path: data/split_data/Consignment_pricing_train.csv
[2023-06-29 21:39:56,008] root - INFO - train data read successfully
[2023-06-29 21:39:56,012] root - INFO - test data read successfully
[2023-06-29 21:39:56,013] root - INFO - model training started
[2023-06-29 21:39:56,069] urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:1234
[2023-06-29 21:39:58,148] urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression'): Retry(total=4, connect=4, read=5, redirect=5, status=5)
[2023-06-29 21:39:58,148] urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026713BEF220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression
[2023-06-29 21:39:58,148] urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 127.0.0.1:1234
[2023-06-29 21:40:00,212] urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression'): Retry(total=3, connect=3, read=5, redirect=5, status=5)
[2023-06-29 21:40:04,217] urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026713D4BBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression
[2023-06-29 21:40:04,218] urllib3.connectionpool - DEBUG - Starting new HTTP connection (3): 127.0.0.1:1234
[2023-06-29 21:40:06,262] urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression'): Retry(total=2, connect=2, read=5, redirect=5, status=5)
[2023-06-29 21:40:14,268] urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026713D4BE20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression
[2023-06-29 21:40:14,268] urllib3.connectionpool - DEBUG - Starting new HTTP connection (4): 127.0.0.1:1234
[2023-06-29 21:40:16,325] urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression'): Retry(total=1, connect=1, read=5, redirect=5, status=5)
[2023-06-29 21:40:32,340] urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026713D6D700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression
[2023-06-29 21:40:32,341] urllib3.connectionpool - DEBUG - Starting new HTTP connection (5): 127.0.0.1:1234
[2023-06-29 21:40:34,397] urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression'): Retry(total=0, connect=0, read=5, redirect=5, status=5)
[2023-06-29 21:41:06,408] urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026713D4BB20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression
[2023-06-29 21:41:06,408] urllib3.connectionpool - DEBUG - Starting new HTTP connection (6): 127.0.0.1:1234
[2023-06-29 21:41:08,463] root - INFO - Exception occured in 'train_evaluate' functionAPI request to http://127.0.0.1:1234/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='127.0.0.1', port=1234): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=RandomForestRegression (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026713D779D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2023-06-29 21:41:08,464] root - INFO - train_evaluate function reported error in the function
